# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_functions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='param',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='自定义参数'),
        ),
    ]
